### ISSUE TITLE
Cart Summary Item Discrepancy 

### ISSUE THREAD

**Issue by ShendelV** [omri-i-b/allied_web#10]
Cart Summary indicates (3items) but Summary View only displays 2 items
Subtotal based on items displayed should reflect $39.29 not 58.25
[Cart Summary Discrepancy.docx](https://github.com/user-attachments/files/17263851/Cart.Summary.Discrepancy.docx)

**Comment by omri-i-b** [comment]
this is an onboarding issue we're tracking
