### ISSUE TITLE
Estimated Weight Not Displaying

### ISSUE THREAD

**Issue by ShendelV** [omri-i-b/allied_web#11]
Under Order Summary /Order Confirmation Page 
Estimated Weight shows 0.0lbs weight should display 6.00lbs 
[Order Confirmation- No EST Weight.docx](https://github.com/user-attachments/files/17264263/Order.Confirmation-.No.EST.Weight.docx)

**Comment by omri-i-b** [comment]
great catch @ShendelV tracking in my ticket 245

**Comment by omri-i-b** [comment]
fixed in 1.7
