### ISSUE TITLE
grade WPB doesn't show on filter but it has WPB parts

### ISSUE THREAD

**Issue by mvallaro0316** [omri-i-b/allied_web#13]
![image](https://github.com/user-attachments/assets/5160738d-05c5-4ad0-8ab9-94d6ed32ca1e)

**Comment by omri-i-b** [comment]
Thanks @mvallaro0316. This will be fixed in the next release. Should have it in the next few hours.

**Comment by omri-i-b** [comment]
fixed in 1.7
