### ISSUE TITLE
Order Summary Estimated Weight Discrepancies 

### ISSUE THREAD

**Issue by ShendelV** [omri-i-b/allied_web#15]
Order Summary Estimated Weight Discrepancies 
Displaying estimated weight of one not quantity ordered 
[Order Summary Estimated Weight Discrepancies.docx](https://github.com/user-attachments/files/17282292/Order.Summary.Estimated.Weight.Discrepancies.docx)

**Comment by omri-i-b** [comment]
fixed in 1.7
