### ISSUE TITLE
Part Grades not Displaying 

### ISSUE THREAD

**Issue by ShendelV** [omri-i-b/allied_web#18]
Under All Products / Flanges (QATest_EC_Dec) /Weld 
not all available grades display in grade selection. Please see attachment 
[Part Grade not displaying.docx](https://github.com/user-attachments/files/17283635/Part.Grade.not.displaying.docx)

**Comment by omri-i-b** [comment]
thanks @ShendelV -- this is being tracked and will be fixed in the next release!

**Comment by omri-i-b** [comment]
fixed in 1.7
