### ISSUE TITLE
HyperLink  Naming Add new address does not display under Shipping 

### ISSUE THREAD

**Issue by ShendelV** [omri-i-b/allied_web#19]
HyperLink  Naming Add new address does not display under Shipping when collapsed. see attachment 
[HyperLink  Naming Add new address  not display under Shipping.docx](https://github.com/user-attachments/files/17283816/HyperLink.Naming.Add.new.address.not.display.under.Shipping.docx)

**Comment by omri-i-b** [comment]
fixed in 1.7
