### ISSUE TITLE
Trying to Complete Purchase

### ISSUE THREAD

**Issue by mvallaro0316** [omri-i-b/allied_web#4]
![image](https://github.com/user-attachments/assets/7d3de2f8-0f45-4589-ab7a-d74030e4f6e5)

**Comment by omri-i-b** [comment]
@mvallaro0316 what was in your cart? Do you still have this basket active?

**Comment by omri-i-b** [comment]
@mvallaro0316 are you still getting this?

**Comment by omri-i-b** [comment]
closing until we see it again - solved by another fix
